/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.VR
{
    public class matrix_3_4 : Message
    {
        public const string RosMessageName = "VR/matrix_3_4";

        public double[] firstRow { get; set; }
        public double[] secondRow { get; set; }
        public double[] thirdRow { get; set; }

        public matrix_3_4()
        {
            this.firstRow = new double[0];
            this.secondRow = new double[0];
            this.thirdRow = new double[0];
        }

        public matrix_3_4(double[] firstRow, double[] secondRow, double[] thirdRow)
        {
            this.firstRow = firstRow;
            this.secondRow = secondRow;
            this.thirdRow = thirdRow;
        }
    }
}
